CrudPrueba/CrudPrueba/Models/Ingresos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingresos
    {
        public int Id { get; set; }
        public string DescripcionMovimiento { get; set; }
        public int IdCampania { get; set; }
        public int IdPersonaRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public decimal Monto { get; set; }
        public string MonedaIso { get; set; }
        public int IdPropiedad { get; set; }
        public int FormaIngreso { get; set; }
        public string CodSubcuenta { get; set; }
        public int IdPersonaVenta { get; set; }
        public int Estado { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdPersonaModificacion { get; set; }
        public Nullable<int> IdCajaEfectivo { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public string NroCheque { get; set; }
        public string NroLanzamiento { get; set; }
        public string PathComprobante { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual CajaEfectivo CajaEfectivo { get; set; }
        public virtual Campania Campania { get; set; }
        public virtual Propiedades Propiedades { get; set; }
        public virtual Subcuentas Subcuentas { get; set; }
    }
}

CrudPrueba/CrudPrueba/Controllers/IngresoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrudPrueba.Models;
using CrudPrueba.Models.TableViewModels;

namespace CrudPrueba.Controllers
{
    // testEntities ob = new testEntities();

    public class IngresoController : Controller
    {
        // GET: Ingreso
        public ActionResult Index()
        {
            List<IngresoTableViewModel> lst = null;
            using (testEntities db = new testEntities())
            {
                lst = (from d in db.Ingresos
                       select new IngresoTableViewModel
                       {
                           Id = d.Id,
                           DescripcionMovimiento = d.DescripcionMovimiento,
                           FechaRegistro = d.FechaRegistro,
                           Monto = d.Monto,
                           MonedaIso = d.MonedaIso,
                           FormaIngreso = d.FormaIngreso,
                           Estado = d.Estado,
                           NroCheque = d.NroCheque,
                           NroLanzamiento = d.NroCheque,
                           PathComprabante = d.PathComprobante
                       }).ToList();
            }
            return View(lst);
        }
    }
}

CrudPrueba/CrudPrueba/Views/Ingreso/Index.cshtml
@model List<CrudPrueba.Models.TableViewModels.IngresoTableViewModel>
 <div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h1>Ingresos</h1>
            </div>
            <div class="pull-right">

                <button type="submit" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                    <i class="fa fa-plus" aria-hidden="true"></i> Agregar
                </button>
            </div>
        </div>
    </div>

    <table id="myTable" class="table" cellspacing="0">
        <thead>
            <tr>
                <th>No</th>
                <th>Descripcion Movimiento</th>
                <th>Fecha de Registro</th>
                <th>Monto</th>
                <th>Moneda</th>
                <th>FormaIngreso</th>
                <th>Estado</th>
                <th>Nro Cheque</th>
                <th>Nro Lanzamiento</th>
                <th>Path Comprobante</th>
                <th width="280px">Action</th>
            </tr>
        </thead>
        <tfoot>
        </tfoot>
        <tbody>
           
        </tbody>

    </table>
     <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet"/>
   @section scripts{
     <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
     <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>

     <script type="text/javascript">

            $(document).ready(function () {

                $('#myTable').DataTable({

                    "ajax": {
                        "type": "GET",
                        "url": "@Url.Action("getdata","Ingreso")",
                        "datatype":"JSON",
                    },
                    "colums": [
                        {data:"Id"},
                        {data:"DescripcionMovimiento"},
                        {data:"FechaRegistro"},
                        {data:"Monto"},
                        {data:"MonedaIso"},
                        {data:"FormaIngreso"},
                        {data:"Estado"},
                        {data:"NroCheque"},
                        {data:"NroLanzamiento"},
                        {data:"PathComprabante"},
                     
                    ]
                });

            });

     </script>
           
   }
   
</div>